site_name: app-rsschool-docs

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Project overview: index.md
  - Developing:
      - Up and running: up_and_running.md
      - API: api.md
      - Backlog: backlog.md
